SELECT "DVD Table: ";
SELECT * FROM dvd;
SELECT "___________________________";
SELECT ""                            ;
SELECT "Customer Table: ";
SELECT * FROM customer;
SELECT "___________________________";
SELECT "";
SELECT "Offers: ";
SELECT * FROM offer;
SELECT "___________________________";